### ISSUE TITLE
Three failing tests for whatthepatch.patch module

### ISSUE THREAD

**Issue by thoward** [cscorley/whatthepatch#1]
I found a small bug with the unified diff parsing, and was planning to submit a PR. In the process of doing that, I decided to run through the tests. However, I found that `test_patch.py`, at current master, has three failing tests.

Should I ignore those and assume that if nothing new breaks, my PR won't be introducing breaking changes?

The failing tests are:

* [test_diff_context_blah](https://github.com/cscorley/whatthepatch/blob/master/tests/test_patch.py#L691)
* [test_diff_default_blah](https://github.com/cscorley/whatthepatch/blob/master/tests/test_patch.py#L728)
* [test_old_style_cvs](https://github.com/cscorley/whatthepatch/blob/master/tests/test_patch.py#L965)

Thanks,
Troy

**Comment by cscorley** [comment]
Yes, these tests have been broken for quite some time. They are examples of real diffs I've found that are not yet handled and are reminders for work yet done. I wouldn't worry about it :)

**Comment by cscorley** [comment]
Fixed these!

Thanks to your intuition in fixing #2, which I used to fix the _blah tests (that I should rename...). :santa:
