### ISSUE TITLE
add support for reverse patching

### ISSUE THREAD

**Issue by graingert** [cscorley/whatthepatch#10]
eg take a patch and switch the +s to -s

**Comment by cscorley** [comment]
Seems like a reasonable suggestion. Is there anything stopping you from doing it anyway? If I recall, it might be as simple as something along the lines of `reversed_changes = [(b, a, line) for a, b, line in original_patch.changes]`. That is, if I'm understanding the objective correctly 😄

**Comment by graingert** [comment]
@cscorley yeah I have that, just working on tests for it now.
