### ISSUE TITLE
No way that a file has been created or deleted

### ISSUE THREAD

**Issue by calixteman** [cscorley/whatthepatch#17]
With the following patch:
diff --git a/titi.txt b/titi.txt
new file mode 100644
--- /dev/null
+++ b/titi.txt
@@ -0,0 +1,1 @@
+hello world

the parse_patch output doesn't give any information about the newly created file (the same for a deleted file)

**Comment by cscorley** [comment]
Is this still an issue?  We have a test case that passes for this: https://github.com/cscorley/whatthepatch/blob/39c8edd34ef30d409d367ffc548d0f0fc5545a18/tests/test_patch.py#L512
https://github.com/cscorley/whatthepatch/blob/39c8edd34ef30d409d367ffc548d0f0fc5545a18/tests/casefiles/git-oneline-add.diff

**Comment by cscorley** [comment]
Closing, no response
