### ISSUE TITLE
If newly added file is empty in Git then parse_patch fails to recognize it.

### ISSUE THREAD

**Issue by momalepd** [cscorley/whatthepatch#18]
Possible fix is at this line: https://github.com/cscorley/whatthepatch/blob/master/whatthepatch/patch.py#L198

Condition should be "while len(lines) > 0:"

Issue:

The diff for empty file creation looks like this:
diff --git a/sample-code/empty_file b/sample-code/empty_file
new file mode 100644
index 0000000..e69de29

**Comment by graingert** [comment]
@momalepd can you make a PR and unit test for this?

**Comment by ronnyli** [comment]
Hi I came here to post this exact issue! Looks like it's been fixed already and now you're at version `0.0.6`. However, when I try to upgrade through pip it says that I'm on the latest version (`0.0.5`). Am I doing something wrong or is it on PyPi's side?

**Comment by cscorley** [comment]
I have yet to push the publish button. I was going to attempt to include
another issue but got behind.
