### ISSUE TITLE
Keep a HISTORY file

### ISSUE THREAD

**Issue by boxed** [cscorley/whatthepatch#25]
Version 0.0.6 isn't backwards compatible with 0.0.5, and that's fine, it's not 1.0, but a HISTORY file detailing the changes would be nice.

**Comment by jayvdb** [comment]
Also there isnt a 0.0.5 release here https://github.com/cscorley/whatthepatch/releases , so `https://github.com/cscorley/whatthepatch/compare/0.0.5...0.0.6` doesnt work

It looks like v0.0.5 is going to be https://github.com/cscorley/whatthepatch/commit/39c8edd34ef30d409d367ffc548d0f0fc5545a18 26 December 2016 which correlates with release history at https://pypi.org/project/whatthepatch/#history

**Comment by cscorley** [comment]
Corrected the tag for 0.0.5, thanks.  Will be starting the HISTORY file.

Is there a specific thing that broke between versions for you?  A new named tuple was introduced, but I did not believe that would break backwards compatibility with the exception of variable unpacking.  I apologize for the inconvenience

**Comment by boxed** [comment]
Well I did indeed unpack the tuple and the size changed. The named tuple is much better and should stop the same issue going forward so it's a good fix.

**Comment by cscorley** [comment]
I apologize for biffing the backwards incompatible change.  I have added a HISTORY file.
